In [4]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8])
print(np.negative(arr1[2:8])) 

[-3 -4 -5 -6 -7 -8]


In [11]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
import numpy as np 
arr2 = np.random.uniform(5,10, (5,3))
arr2

array([[6.91654419, 9.64956305, 5.79207357],
       [9.95935034, 5.31355522, 8.67705497],
       [5.45610221, 8.26934247, 9.04847135],
       [9.88787671, 9.52739144, 6.00386233],
       [8.0718899 , 5.7621937 , 5.84764186]])

In [14]:
# Given a 1D array, add 1 to every alternate element.
import numpy as np
arr3 = np.array([1,2,3,4,5,6,7,8,9])
for x in range(len(arr3)):
    arr3[x]+=1 #loop at the index i
print(arr3)

[ 2  3  4  5  6  7  8  9 10]


In [22]:
# Given a 2D array, flatten it to a 1D array.
import numpy as np
arr4 = np.array([[1,2,3,4], [2,3,4,5]]) # must be the same amount of array 
arr4.flatten()

array([1, 2, 3, 4, 2, 3, 4, 5])

In [29]:
# Convert a 1D array of 20 grayscale image values into a 2D array of 5x4 shape.
import numpy as np
arr5 = np.arange(21).reshape((7,3))
arr5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [4]:
# replace odd numbers in a 3 dimensional array with even number

import numpy as np
np.random.seed(100)
store = np.random.normal(5,10,27).astype(int)

In [6]:
store=store.reshape((3,3,3))


AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [40]:
store


array([[[-12,   8,  16],
        [  2,  14,  10],
        [  7,  -5,   3]],

       [[  7,   0,   9],
        [  0,  13,  11],
        [  3,   0,  15]],

       [[  0,  -6,  21],
        [ 20,   2,  -3],
        [  6,  14,  12]]])

In [28]:
#Exercise 2 create a 2 dimension numpy array to fill with 0's and 1's but the output should look like a checker board
'''
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
'''
# Solution

import numpy as np
def checkerBoard(n):
    print("Lets play Chess baby")
    arr6 = np.zeros((n,n), dtype=int)
    
    arr6[1::2, ::2] = 1
    arr6[::2, 1::2] = 1
     
    for i in range(n):
        for j in range(n):
            print(arr6[i][j], end=" ")
        print()
n = 8
checkerBoard(n)

Lets play Chess baby
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [34]:
#Exercise 3 Consider a numpy array of shape (200,3)
# We need to extract those rows which are symmetrical.
# [1,2,1] is symmetrical [1,2,3] isnt

Z = np.random.randint(0,5,(200,3))
# [0,2,0]
# solution 1
isSymetric = (Z[:, 0] == Z[:, 2])
symmetricalarr = isSymetric
print(symmetricalarr)

[False False False False False False False  True False False False False
 False False False False False False False False False False False False
  True False False False  True  True False  True False False False False
 False False False False False False False  True  True False False  True
 False False False  True  True False  True False False False False False
  True False False False False  True False False False False False False
 False False False False False False False False False  True False  True
 False False False False  True  True  True False False False False False
 False False  True False False False  True False False  True False False
  True  True False False  True False False False False  True False False
 False  True False  True False False  True  True  True False False False
  True False False  True  True  True False  True False False  True False
  True False  True False  True False False False False  True False False
 False False  True  True False False False False Fa

In [30]:
# Exercise 4 Make the above array symmetrical


In [ ]:
Z

array([[4, 2, 4],
       [3, 3, 3],
       [0, 1, 0],
       [2, 3, 2],
       [4, 2, 4],
       [3, 1, 3],
       [4, 3, 4],
       [2, 2, 2],
       [2, 4, 2],
       [2, 2, 2],
       [2, 2, 2],
       [4, 2, 4],
       [3, 1, 3],
       [0, 1, 0],
       [4, 2, 4],
       [3, 1, 3],
       [3, 0, 3],
       [1, 3, 1],
       [4, 2, 4],
       [3, 4, 3],
       [2, 0, 2],
       [0, 4, 0],
       [4, 4, 4],
       [0, 1, 0],
       [4, 2, 4],
       [3, 2, 3],
       [3, 4, 3],
       [3, 1, 3],
       [0, 0, 0],
       [4, 2, 4],
       [2, 1, 2],
       [1, 2, 1],
       [0, 2, 0],
       [4, 2, 4],
       [2, 1, 2],
       [2, 4, 2],
       [3, 4, 3],
       [1, 3, 1],
       [2, 2, 2],
       [1, 2, 1],
       [0, 3, 0],
       [4, 2, 4],
       [0, 0, 0],
       [3, 2, 3],
       [1, 0, 1],
       [0, 0, 0],
       [1, 2, 1],
       [3, 1, 3],
       [3, 2, 3],
       [4, 4, 4],
       [4, 3, 4],
       [3, 2, 3],
       [3, 2, 3],
       [2, 0, 2],
       [1, 4, 1],
       [0,