In [ ]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.


In [ ]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.


In [ ]:
# Given a 1D array, add 1 to every alternate element.


In [ ]:
# Given a 2D array, flatten it to a 1D array.


In [ ]:
# Convert a 1D array of 20 grayscale image values into a 2D array of 5x4 shape.


In [ ]:
# replace odd numbers in a 3 dimensional array with even number

import numpy as np
np.random.seed(100)
store = np.random.normal(5,10,27).astype(int)


In [ ]:
store=store.reshape((3,3,3))

In [ ]:
store

array([[[-12,   8,  16],
        [  2,  14,  10],
        [  7,  -5,   3]],

       [[  7,   0,   9],
        [  0,  13,  11],
        [  3,   0,  15]],

       [[  0,  -6,  21],
        [ 20,   2,  -3],
        [  6,  14,  12]]])

In [ ]:
#Exercise 2 create a 2 dimension numpy array to fill with 0's and 1's but the output should look like a checker board
'''
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
'''
# Solution



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Exercise 3 Consider a numpy array of shape (200,3)
# We need to extract those rows which are symmetrical.
# [1,2,1] is symmetrical [1,2,3] isnt

Z = np.random.randint(0,5,(200,3))
# [0,2,0]
# solution 1


[[3 3 3]
 [4 2 4]
 [4 3 4]
 [4 2 4]
 [4 2 4]
 [0 1 0]
 [2 1 2]
 [2 4 2]
 [3 2 3]
 [4 3 4]
 [0 3 0]
 [0 0 0]
 [3 2 3]
 [3 0 3]
 [1 0 1]
 [1 2 1]
 [3 4 3]
 [2 0 2]
 [2 3 2]
 [2 4 2]
 [4 1 4]
 [1 3 1]
 [2 2 2]
 [1 2 1]
 [0 1 0]
 [0 0 0]
 [3 4 3]
 [3 1 3]
 [2 3 2]
 [4 3 4]
 [3 1 3]
 [0 3 0]
 [3 4 3]
 [3 3 3]
 [0 4 0]
 [0 4 0]
 [4 1 4]
 [1 1 1]
 [3 4 3]
 [3 1 3]
 [3 4 3]]


In [ ]:
# Exercise 4 Make the above array symmetrical


In [ ]:
Z

array([[4, 2, 4],
       [3, 3, 3],
       [0, 1, 0],
       [2, 3, 2],
       [4, 2, 4],
       [3, 1, 3],
       [4, 3, 4],
       [2, 2, 2],
       [2, 4, 2],
       [2, 2, 2],
       [2, 2, 2],
       [4, 2, 4],
       [3, 1, 3],
       [0, 1, 0],
       [4, 2, 4],
       [3, 1, 3],
       [3, 0, 3],
       [1, 3, 1],
       [4, 2, 4],
       [3, 4, 3],
       [2, 0, 2],
       [0, 4, 0],
       [4, 4, 4],
       [0, 1, 0],
       [4, 2, 4],
       [3, 2, 3],
       [3, 4, 3],
       [3, 1, 3],
       [0, 0, 0],
       [4, 2, 4],
       [2, 1, 2],
       [1, 2, 1],
       [0, 2, 0],
       [4, 2, 4],
       [2, 1, 2],
       [2, 4, 2],
       [3, 4, 3],
       [1, 3, 1],
       [2, 2, 2],
       [1, 2, 1],
       [0, 3, 0],
       [4, 2, 4],
       [0, 0, 0],
       [3, 2, 3],
       [1, 0, 1],
       [0, 0, 0],
       [1, 2, 1],
       [3, 1, 3],
       [3, 2, 3],
       [4, 4, 4],
       [4, 3, 4],
       [3, 2, 3],
       [3, 2, 3],
       [2, 0, 2],
       [1, 4, 1],
       [0,