In [2]:
# slicing, indexing, shape

# axes

# np.  arange, linspace, zeros, etc

# 2 dimension

# stats methods, min, max, mean, mode, std, sum,

In [3]:
import numpy as np

In [4]:
!pip install numpy

In [5]:
np1 = np.array([1,2,3,4,5,6,7,8,9], ndmin = 2)

In [6]:
print(np.ndim)

<function ndim at 0x000001F202FFC2C0>


In [7]:
#Return 2,3,4,5
print(np1[1:5])

[]


In [8]:
#Print till the end of line
print(np1[6:])

[]


In [9]:
#Return Negative Slices
#print 4,5
print(np1[-6:-4])

[]


In [10]:
#Steps
print(np1[1:5]) #2-5
print(np1[1:5:2])#2-5 in steps of 2

[]
[]


In [11]:
#Seps on entire array
print(np1[::2])#every other array

[[1 2 3 4 5 6 7 8 9]]


In [12]:
# SLice a 2-d array
np2 = np.array([
    [1,2,3,4,5], # 1st row = 0
    [6,7,8,9,10]]) # 2nd column = 1
#2

In [13]:
print(np2[0,1])

2


In [14]:
print(np2[1,2])
#8

8


In [15]:
print(np2[0,3])
#4

4


In [16]:
#Pull out a single item
print(np2[1,2])# 1 is the first array with a , of the item 2

8


In [17]:
#Slice a 2-d array = 4 and 10
print(np2[0:5, 2:4])

[[3 4]
 [8 9]]


In [18]:
arr = np.array([[[1, 2, 3],# the first dimenstion containg 2 array ([],[])
                [4, 5, 6]], 
                [[7, 8, 9],# the second dimenstion containg 2 array ([],[])
                [3, 3, 4]],
                [[2, 1, 3],# the third dimenstion containg 2 array ([],[])
                [5, 6, 8]]]) 

In [19]:
print(arr[2])
print(arr[0])
print(arr[0, 
          1, 
          2])
print(arr[1:0])

[[2 1 3]
 [5 6 8]]
[[1 2 3]
 [4 5 6]]
6
[]


In [20]:
print(arr[0:2, 1:3])

[[[4 5 6]]

 [[3 3 4]]]


In [21]:
print(arr[:,-1]) # Gets the last column of every row

[[4 5 6]
 [3 3 4]
 [5 6 8]]


In [22]:
print(arr>5)

[[[False False False]
  [False False  True]]

 [[ True  True  True]
  [False False False]]

 [[False False False]
  [False  True  True]]]


In [23]:
print(arr[::-1])

[[[2 1 3]
  [5 6 8]]

 [[7 8 9]
  [3 3 4]]

 [[1 2 3]
  [4 5 6]]]


In [24]:
result = np.mean(arr, axis=1)

In [25]:
print(result)

[[2.5 3.5 4.5]
 [5.  5.5 6.5]
 [3.5 3.5 5.5]]


In [26]:
arr1 = np.array([[1, 2, 3],[4, 5, 6],
                [7, 8, 9]])

In [27]:
print(arr[1, 0])
print(arr[0,1,0])

[7 8 9]
4


In [28]:
arr2 = np.array([[22,34,23,22],
                [2,34,56,3],
                [77,58,90,33]])
print(arr2[2] + arr2[1])
print(arr2[0])
print(arr2[0] * arr2[1])

[ 79  92 146  36]
[22 34 23 22]
[  44 1156 1288   66]


In [29]:
#Indexing
arr3 = np.array([1, 2, 3, 4]) # <----- is an array
print([arr3[1]]) #<------ print the second element from the array

[2]


In [30]:
#Slicing
arr4 = np.array([[1,2,4,5,6],
                 [2,3,5,6,7]])

In [37]:
#slice elements in the second array index 1-5
print(arr4[1:5])

[[2 3 5 6 7]]


In [35]:
#slice elements in index 0-5
print(arr4[0:1])

[[1 2 4 5 6]]


In [42]:
#slice to the end of the array
#numbers larger than array slice till the end
print(arr4[:4])
print(arr4[:2])

[[1 2 4 5 6]
 [2 3 5 6 7]]
[[1 2 4 5 6]
 [2 3 5 6 7]]


In [61]:
#Negative Slicing
print(arr4[::,-1])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
#